window.ENV = {
    GEMINI_FLASH_KEY: 'YOUR_GEMINI_FLASH_KEY',
    GEMINI_BLIND_KEY: 'YOUR_GEMINI_BLIND_KEY',
    GPT5_TOKEN: 'YOUR_GPT5_TOKEN',
    GROK_TOKEN: 'YOUR_GROK_TOKEN',
    GOOGLE_CLIENT_ID: 'YOUR_GOOGLE_CLIENT_ID'
};
